image:https://raw.githubusercontent.com/freight-trust/branding/22cafe8e7f71594a5f4ded9fedc9b9af308ba1e9/sm_banner.svg[Freight Trust Banner,900,role="left"]


= Corporate PKI and GPG
:url-project: https://freighttrust.com
:url-docs: https://github.com/freight-trust/pki
:url-org: https://github.com/freight-trust
:url-group: {url-org}/pki
:url-site-readme: {url-group}/pki/blob/master/README.adoc
:url-freighttrust: https://freighttrust.com
:public-key: /gpg/6F6EB43E.asc
:active-key: {url-group}{public-key}


=== Signing Key

`curl https://raw.githubusercontent.com/freight-trust/pki/master/6F6EB43E.asc --output 6F6EB43E.asc`

http://keys.gnupg.net/pks/lookup?search=freighttrust&fingerprint=on&op=index[verify on keys.gnupgp]


=== Docker Trust Signature


``freight-trust`` key with ``ID: fbda181``

```bash
-----BEGIN PUBLIC KEY-----
role: freight-trust

MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEXRTPyINRxXaIs+tXqGv99Fnm83Jy
DR8xgYoRFTzTMF4V13jx43Fn9nFJLfmdqyFovngiedFIm9htFve9qToAZg==
-----END PUBLIC KEY-----
```



== PGP
Public Key Infrastructure and other Cryptographic Signing Instruments

```bash
pub   rsa4096 2020-06-04 [SC] [expires: 2024-06-04]
      858023A92C8DA82FB996BB37361D5A506F6EB43E
uid           [ultimate] sam bacha <sam@freighttrust.com>
uid           [ultimate] Freight Trust Corp <sam@freighttrust.com>
sub   rsa4096 2020-06-04 [E] [expires: 2024-06-04]
sub   rsa4096 2020-06-16 [S] [expires: 2022-08-29]'

      8580 23A9 2C8D A82F B996  BB37 361D 5A50 6F6E B43E
```

The playbook and instructions are located in {url-site-readme}[Freight Trust & Clearing Corporation].

=== Usage

Example

```bash
$ gpg --verify besu-xt.asc
gpg: assuming signed data in 'besu-xt'
gpg: Signature made Thu Jun 25 07:01:55 2020 PDT
gpg:                using RSA key C00B2090F23C5629029111CBF5D2A7216C51FB94
gpg: Good signature from "sam bacha <sam@freighttrust.com>" [ultimate]
gpg:                 aka "Freight Trust Corp <sam@freighttrust.com>" [ultimate]
```
Where {url-group}{public-key} is = C00B2090F23C5629029111CBF5D2A7216C51FB94

=== Resources

* {url-project}[Freight Trust Network Project]
* {url-docs}[Freight Trust Docs]
* {url-org}[Freight Trust & Clearing Repositories]

== Copyright and License

Copyright (C) 2020 FreightTrust & Clearing Corporation. and individual Freight Trust Network Project contributors.

Use of this documentation is granted under a dual-license, MIT and Apache-2.0

== License
MIT
Apache-2.0

Development of the Freight Trust Network is led and sponsored by {url-freighttrust}[FreightTrust & Clearing Corporation].
